V0.9.0
qytiz/TestGuru pull request #10
Opened 2021-02-09 11:38 UTC by qytiz

authorization added, added new nav button for users, adding loging and logout pages, now test Authors will be fill automaticly from current user, added sessions.

2021-02-09 14:30 UTC, VidgarVii requested changes

2021-02-09 14:30 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +      redirect_to login_path
хорошим тонном будет оставлять сообщение почему юзера отправили логиниться

2021-02-09 14:30 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +      cookies[:return_to_method] = request.method.to_sym
не думаю что запись return_to_method понадобиться.

2021-02-09 14:30 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies[:return_to] || root_path
cookies можно сразу удалять. Запись больше не понадобится

2021-02-09 14:30 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +    else
redirect_to должно быть последнем что должен сделать. тут удаление кук не произайдет

2021-02-09 14:30 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    if @test.save!
current_user.own_test.build(...)

2021-02-10 05:57 UTC, VidgarVii requested changes

2021-02-10 05:57 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    if @test.save!
я тебе просто пример показад, как лаконичней создавать дочерние объекты. Не надо было копипастить метод под чистую и писать ужасную реализацию. 
Читай методы запросов http://rusrails.ru/active-record-associations#metody-dobavlyaemye-has_many
У всех ассоциациях

2021-02-10 05:57 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies.delete(:return_to)
посмотри что возвращает cookies.delete(:return_to) и исправь код. За одно и убери удаление кук в лишних местах.

2021-02-10 08:52 UTC, qytiz commented on app/controllers/tests_controller.rb
> +    if @test.save!
К сожалению данный метод возвращает объект без id но я смог исправить это с помощью скрытого поля

2021-02-10 14:48 UTC, VidgarVii requested changes

2021-02-10 14:48 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies.delete(:return_to)|| tests_path
пробел забыл

2021-02-10 14:48 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    if @test.save!
ни каких скрытых полей
какое id тебе нужно?

2021-02-10 14:48 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins('JOIN test_passages ON test_passages.test_id = tests.id').where(tests: { level: level },
вместо sql строки используй символ

2021-02-10 15:32 UTC, qytiz commented on app/controllers/application_controller.rb
> +    cookies.delete(:return_to)|| tests_path
@VidgarVii Отправил новый вариант

2021-02-11 06:08 UTC, VidgarVii requested changes

2021-02-11 06:08 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    if @test.save!
если тест не запишется в базу, то до 21 сервер выбросит ошибку из-за bang метода save!

2021-02-11 07:51 UTC, merged