12th task
qytiz/TestGuru pull request #13
Opened 2021-02-16 13:13 UTC by qytiz

2021-02-16 20:01 UTC, VidgarVii commented on app/javascript/packs/application.js
> +console.log('Hello from application.js')
Привет привет. Можно удалять

2021-02-16 20:01 UTC, VidgarVii commented on app/javascript/packs/utilites/confirming.js
> +            var confirm = e.target.value
var deprecatad используй const/let

2021-02-17 06:28 UTC, VidgarVii requested changes

2021-02-17 06:28 UTC, VidgarVii commented on app/javascript/packs/utilites/confirming.js
> +            var matchConfirmation = e.target.parentNode.querySelector(".octicon-check")
при каждом изменении поля происходит поиск элементов. Эта операция очень дорогая и долгая. Выноси поиск элементов за пределы события

2021-02-17 06:28 UTC, VidgarVii commented on app/javascript/packs/utilites/confirming.js
> +        confirm_field.addEventListener('change', (e) => {
1 не сокращай
2 для 1 параметра скобки можно убрать
addEventListener('change', event => {})

2021-02-17 06:28 UTC, VidgarVii commented on app/javascript/packs/utilites/confirming.js
> +        confirm_field.addEventListener('change', (e) => {
используй ковычки

2021-02-17 06:28 UTC, VidgarVii commented on app/javascript/packs/utilites/confirming.js
> +})
а что с ООП не так?

2021-02-17 06:28 UTC, VidgarVii commented on Gemfile
> +gem 'jquery-rails'
ты ведь не используешь jquery. Да и он тут не нужен

2021-02-17 06:28 UTC, VidgarVii commented on app/javascript/packs/utilites/sorting.js
> +}
простое решение сортировки
https://plnkr.co/edit/vSOTyAmS8sJtH0g0?p=preview&preview

2021-02-17 06:28 UTC, VidgarVii commented on app/views/tests/index.html.erb
> +        </th>
а как юзер поймёт, что таблицу можно сортировать, если стрелки по умолчанию скрыты?

2021-02-18 16:45 UTC, VidgarVii commented on app/controllers/User/sessions_controller.rb
>      super
с начало создают юзера. А затем приветствуют. И все эти проверки на current_user будут не к чему

2021-02-18 16:45 UTC, VidgarVii commented on app/javascript/packs/utilites/confirming.js
> +})
с отступами беда. Везде в проекте используй 2 пробела

2021-02-18 16:45 UTC, VidgarVii commented on app/javascript/packs/utilites/sorting.js
> +    let arrowDown = document.querySelector('.octicon-arrow-down');
так как не переопределяешь переменные, то лушче их заменить на const

2021-02-18 16:45 UTC, VidgarVii commented on app/javascript/packs/utilites/sorting.js
> +    }
тут можно в 1 строчку написать
if (control) control.addEventListener('click', sortRowsByTitle)

2021-02-18 16:45 UTC, VidgarVii commented on app/javascript/packs/utilites/sorting.js
> +}
нет пустой строки
где отступы внутри блока?

2021-02-18 17:22 UTC, qytiz commented on app/controllers/User/sessions_controller.rb
>      super
К сожалению без этих проверок ничего не работает, при неудачной авторизации пользователя выводится сообщение об отсутвие "current_user"

2021-02-19 20:17 UTC, merged