3rd-Task v0.2.0
qytiz/TestGuru pull request #4
Opened 2020-12-18 18:27 UTC by qytiz

2020-12-18 21:16 UTC, VidgarVii requested changes

2020-12-18 21:16 UTC, VidgarVii commented on app/models/test.rb
> +        .order(title: :ASC)
desc

2020-12-18 21:16 UTC, VidgarVii commented on app/models/test.rb
> +        .where('categories.title': category)
условия на таблицы можно (и рекомендуется, где это приемлимо) накладывать через хэши
```ruby
where(categories: { title: ... })
```
их проще изменять и легче читать

2020-12-18 21:16 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins('JOIN categories ON test.category_id = categories_id')
можно (и рекомендуется)  писать так:
```ruby
joins(...)...
```
т.е. без явного указания объекта у которого вызывается метод
потому что в данном случае объектом является класс `Test` и ему равен `self` внутри класс-метода
по дефолту, при вызове метода без указания объекта он вызывается у `self`, т.е. в текущем варианте как раз у `Test`

2020-12-18 21:16 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins('INNER JOIN').where('testing_histories.user_id': id, level: level)
соединение таблиц должно происходить в методе joins

2020-12-18 21:16 UTC, VidgarVii commented on db/migrate/20201218160838_create_complited_history_tests.rb
> +    create_table :complited_history_tests do |t|
1 completed
2 не совсем очевидное название для соединительной таблицы
Далее в уроках модель будет называться TestPassege. Советую использовать данное название, чтобы не путаться

2020-12-18 21:16 UTC, VidgarVii commented on db/migrate/20201218181639_create_create_complited_history_tests.rb
> +end
я уже сегодня говорил, что надо проверять свой же код

2020-12-18 21:16 UTC, VidgarVii commented on db/seeds.rb
> +answer = Answer.new(title: 'Ответ', correct: false, questions_id: 1)
1. очень странный тест с 1 вопросом, который имеет 1 ответ. надо больше данных. Хотя бы 3-4 вопроса с 3-4 ответом
2. Порождение объекта не добавит записи в БД. 
3. Проверяй ВСЁ руками!

2020-12-21 15:25 UTC, VidgarVii requested changes

2020-12-21 15:25 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins('JOIN TestPassege on TestPassege.user_id = user_id').where(tests:{level: level},TestPassege:{user_id:id})
нет такой таблицы TestPassege

2020-12-21 15:25 UTC, VidgarVii commented on db/migrate/20201210151040_create_tests.rb
>        t.references :users, null: false, foreign_key: true
надо писать в единственном числе. references это алиас belongs_to

2020-12-21 15:25 UTC, VidgarVii commented on db/seeds.rb
> +  {level: 1, title: 'RUBY-TEST', categories_id: 1, users_id: 1}
categories_id: 1 - не факт, что такой ид будет в наличии. Вытаскивай данные из переменной

2020-12-21 15:25 UTC, VidgarVii commented on db/seeds.rb
> +user = User.create!([
тут создастся 2 юзера. А переменная почему-то в единственном числе

2020-12-21 15:26 UTC, VidgarVii requested changes

2020-12-21 15:26 UTC, VidgarVii commented on db/seeds.rb
> +  ])
хорошо бы защитить базу от дублирующих запусков сидов

2020-12-22 09:01 UTC, qytiz commented on db/seeds.rb
> +  ])
А разве 8 строка не защитит от дублирования?

2020-12-24 13:17 UTC, merged