V0.7.0
qytiz/TestGuru pull request #8
Opened 2021-02-02 13:31 UTC by qytiz

Adding UI, fixing bugs, adding footer, adding new actions, adding new helpers, adding new views.

2021-02-02 18:28 UTC, VidgarVii requested changes

2021-02-02 18:28 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>    end
согласно ДЗ этот экшен не нужен

2021-02-02 18:28 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :test_id)
test_id должен приходить параметрами запроса, а не формой

2021-02-02 18:28 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  end
User.all может современем положить сервер

2021-02-02 18:28 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    if @test.save!
bang! метод не вернёт false при ошибке валидации, а выбросит ActiveRecord::RecordInvalid и до след строчки дело не дойдёт

2021-02-02 18:28 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +    end
else if категорически не используется. Ни каких императивных подходов.
if это уже не хорошо, но без него сложно писать читаемый код. 

по вопросу можно определить персистентный это объект или новый. Больше проверок ни каких не надо

2021-02-02 18:28 UTC, VidgarVii commented on config/initializers/version.rb
> +  VERSION = '0.7.0'
freeze

2021-02-02 18:28 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +        "#{Date.today.year}."
rails way говорит, что бы не случилось. Всегда используй временную зону)

2021-02-02 18:28 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +        data="#{author}.<a href='https://github.com/#{author}/#{repo}'>#{repo}.</a>"
используй хелпер link_to

2021-02-02 18:59 UTC, qytiz commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :test_id)
@VidgarVii, но так как это редактирование вопроса то тут добавлена возможность смены теста к которому принадлежит данный вопрос

2021-02-02 19:19 UTC, qytiz commented on app/controllers/tests_controller.rb
> +  end
@VidgarVii,Это временное решения до создания аутентификации поскольку сейчас это смена  пользователя создавшего тест (Разумеется что в финальном варианте он будет задаваться автоматически)

2021-02-03 07:22 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +        "#{Time.current.year}."
не надо оборачивать число в строку
в ruby отступы 2 пробела

2021-02-03 07:22 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    end
github_url должен вернуть github url.
Достаточно link_to repo,"https://github.com/#{author}/#{repo}"
html_safe не нужен

2021-02-03 07:22 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +    end
убери лишний параметр. Приведи код в красивый вид

2021-02-03 07:22 UTC, VidgarVii commented on app/views/tests/show.html.erb
> +</table>
семантически таблица содержит шапку thead и тело tbody

2021-02-03 13:53 UTC, VidgarVii requested changes

2021-02-03 13:53 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @users = User.all # TODO: После создания авторизации переделать на авто выбор
добавь автора в экшен создании теста

2021-02-03 13:53 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @test = Test.find(params[:id])
Test.find(params[:id]) должен быть отдраен

2021-02-03 13:53 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    end
не исправил полность. Название метода не стыкуется с реализацией. 
Где красивые отступы?
Внешние ссылки должны открываться с новой влкадки и иметь опцию rel=nofollow

2021-02-03 13:53 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :passing_users, dependent: :destroy, through: :test_passages, source: :user
в ассоциации has_many through достаточного 1 dependent

2021-02-03 13:53 UTC, VidgarVii commented on app/models/user.rb
> +  scope :ended_on_level, lambda { |level|
1 ну и названице) 
2 скоуп всегда пишут в 1 строку. И он должен быть простым. В противном случаи пишут методы класса
3 тут вообще ошибка. Смотри первые ДЗ

2021-02-04 13:10 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    redirect_to test_path(@question.test_id)
аргумент должен быть объектом теста, а не его ид

2021-02-04 13:10 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +      "Create New #{question.title} Question"
тут question.title будет nil

2021-02-04 13:10 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<% end %>
отступы 2 пробела

2021-02-04 13:10 UTC, VidgarVii commented on app/views/tests/show.html.erb
> +<% if @test.questions.count > 0 %>
.present?

2021-02-08 13:41 UTC, merged